name: Deploy Sandbox

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Zip Artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Customers.zip .
          
      - name: Upload Stage
        run: |
          curl -X PATCH --verbose -u clover:clover --header "Content-Type: application/zip" --header "X-Requested-By: Clover REST API documentation" --data-binary @${{ github.workspace }}/Customers.zip "https://cloverdx.20.108.225.66.nip.io/clover/api/rest/v1/sandboxes/Customers/zip"